Feature/KYV-377 recreate subscription
City-of-Helsinki/verkkokauppa-experience-api pull request #128
Opened 2022-02-11 06:58 UTC by wpamb

2022-02-11 08:36 UTC, severikupari1 requested changes

2022-02-11 08:36 UTC, severikupari1 commented on packages/order-backend/src/subscription/types.ts
> +  meta: SubscriptionItemMeta[]
Is meta optional?

2022-02-11 08:38 UTC, severikupari1 commented
Can you create automation tests for this case functional/unit?

2022-02-11 09:06 UTC, wpamb commented on packages/order-backend/src/subscription/types.ts
> +  meta: SubscriptionItemMeta[]
Shouldn't be

2022-02-11 09:07 UTC, wpamb commented on packages/order-backend/src/subscription/types.ts
> +  label: string
Might be. The typings in general are quite lacking with a lot of values possibly missing etc etc

2022-02-11 09:08 UTC, wpamb commented on packages/order-experience-api/src/api/recreateSubscription.ts
> +    const newSubscription = await createSubscription({
That's a good idea. I'll fix this

2022-02-11 09:08 UTC, wpamb commented on packages/order-experience-api/src/api/recreateSubscription.ts
> +      billingStartDate: oldSubscription.endDate,
The ticket at least has specified it as old subscription's endDate

2022-02-14 07:44 UTC, severikupari1 approved these changes

2022-02-14 07:45 UTC, merged